apiVersion: v2
name: bridge-system
description: Web app for bridge bidding system documentation
type: application
version: 0.1.0
appVersion: "0.1.0"
home: https://github.com/cholewa1992/bridge-system
keywords:
  - bridge
  - bidding
  - webauthn
maintainers:
  - name: cholewa1992
