# fly.toml app configuration file generated for bridge-backend on 2026-05-12T21:08:31+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bridge-backend'
primary_region = 'ams'

[build]
  dockerfile = 'Dockerfile'

[deploy]
  strategy = 'rolling'

[env]
  COOKIE_SECURE = 'true'
  CORS_ORIGINS = 'https://bridge-frontend.fly.dev'
  SERVER_ADDRESS = '::'
  WEBAUTHN_ORIGINS = 'https://bridge-frontend.fly.dev'
  WEBAUTHN_RP_ID = 'bridge-frontend.fly.dev'
  WEBAUTHN_RP_NAME = 'Bridge System'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '1gb'
