apiVersion: v1
kind: Service
metadata:
  name: {{ include "bridge-system.frontendName" . }}
  labels:
    {{- include "bridge-system.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/component: frontend
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bridge-system.frontendName" . }}
  labels:
    {{- include "bridge-system.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.frontend.enabled }}
  replicas: {{ .Values.replicas.frontend }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/component: frontend
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "bridge-system.labels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
    spec:
      containers:
        - name: frontend
          image: {{ include "bridge-system.frontendImage" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          resources:
            {{- toYaml .Values.resources.frontend | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 5
