apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "bridge-system.backendName" . }}
  labels:
    {{- include "bridge-system.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: backend
      app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "bridge-system.frontendName" . }}
  labels:
    {{- include "bridge-system.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: frontend
      app.kubernetes.io/instance: {{ .Release.Name }}
